export const occupations = [
    {
        label: '--select one---',
        value: '',
        header: false,
    },
    {
        label: 'Healthcare Practitioners and Technical Occupations:',
        value: 'header1',
        header: true,
    },
    { label: 'Chiropractor', value: 'chiropractor', header: false },
    { label: 'Dentist', value: 'dentist', header: false },
    { label: 'Dietitian or Nutritionist', value: 'dietitian', header: false },
    { label: 'Optometrist', value: 'optometrist', header: false },
    { label: 'Pharmacist', value: 'pharmacist', header: false },
    { label: 'Physician', value: 'physician', header: false },
    { label: 'Physician Assistant', value: 'physician_assistant', header: false },
    { label: 'Podiatrist', value: 'podiatrist', header: false },
    { label: 'Registered Nurse', value: 'RN', header: false },
    { label: 'Therapist', value: 'therapist', header: false },
    { label: 'Veterinarian', value: 'veterinarian', header: false },
    { label: 'Health Technologist or Technician', value: 'health_technician', header: false },
    {
        label: 'Other Healthcare Practitioners and Technical Occupation',
        value: 'other_health',
        header: false,
    },
    { label: 'Healthcare Support Occupations:', value: 'header2', header: true },
    { label: 'Nursing, Psychiatric, or Home Health Aide', value: 'homehealth', header: false },
    {
        label: 'Occupational and Physical Therapist Assistant or Aide',
        value: 'physical_therapist',
        header: false,
    },
    { label: 'Other Healthcare Support Occupation', value: 'other_health_support', header: false },
    {
        label: 'Business, Executive, Management, and Financial Occupations:',
        value: 'business_header',
        header: true,
    },
    { label: 'Chief Executive', value: 'ceo', header: false },
    { label: 'General and Operations Manager', value: 'gm', header: false },
    {
        label: 'Advertising, Marketing, Promotions, Public Relations, and Sales Manager',
        value: 'sales_manager',
        header: false,
    },
    {
        label: 'Operations Specialties Manager (e.g., IT or HR Manager)',
        value: 'operations_manager',
        header: false,
    },
    { label: 'Construction Manager', value: 'construction_manager', header: false },
    { label: 'Engineering Manager', value: 'engineering_manager', header: false },
    { label: 'Accountant, Auditor', value: 'accountant', header: false },
    {
        label: 'Business Operations or Financial Specialist',
        value: 'business_operations',
        header: false,
    },
    { label: 'Business Owner', value: 'self_employed', header: false },
    {
        label: 'Other Business, Executive, Management, Financial Occupation',
        value: 'other_business',
        header: false,
    },
    { label: 'Architecture and Engineering Occupations:', value: 'header3', header: true },
    { label: 'Architect, Surveyor, or Cartographer', value: 'architect', header: false },
    { label: 'Engineer', value: 'engineer', header: false },
    {
        label: 'Other Architecture and Engineering Occupation',
        value: 'other_engineer',
        header: false,
    },
    { label: 'Education, Training, and Library Occupations:', value: 'header4', header: true },
    { label: 'Postsecondary Teacher (e.g., College Professor)', value: 'professor', header: false },
    {
        label: 'Primary, Secondary, or Special Education School Teacher',
        value: 'teacher',
        header: false,
    },
    { label: 'Other Teacher or Instructor', value: 'other_teacher', header: false },
    {
        label: 'Other Education, Training, and Library Occupation',
        value: 'other_education',
        header: false,
    },
    { label: 'Other Professional Occupations:', value: 'header5', header: true },
    {
        label: 'Arts, Design, Entertainment, Sports, and Media Occupations',
        value: 'media',
        header: false,
    },
    { label: 'Computer Specialist, Mathematical Science', value: 'software', header: false },
    {
        label: 'Counselor, Social Worker, or Other Community and Social Service Specialist',
        value: 'social_worker',
        header: false,
    },
    { label: 'Lawyer, Judge', value: 'lawyer', header: false },
    {
        label: 'Life Scientist (e.g., Animal, Food, Soil, or Biological Scientist, Zoologist)',
        value: 'life_scientist',
        header: false,
    },
    {
        label: 'Physical Scientist (e.g., Astronomer, Physicist, Chemist, Hydrologist)',
        value: 'animal_scientist',
        header: false,
    },
    {
        label: 'Religious Worker (e.g., Clergy, Director of Religious Activities or Education)',
        value: 'religious_worker',
        header: false,
    },
    { label: 'Social Scientist and Related Worker', value: 'social_scientist', header: false },
    { label: 'Other Professional Occupation', value: 'other_professional', header: false },
    { label: 'Office and Administrative Support Occupations:', value: 'header6', header: true },
    { label: 'Supervisor of Administrative Support Workers', value: 'supervisor', header: false },
    { label: 'Financial Clerk', value: 'clerk', header: false },
    { label: 'Secretary or Administrative Assistant', value: 'secretary', header: false },
    {
        label: 'Material Recording, Scheduling, and Dispatching Worker',
        value: 'dispatcher',
        header: false,
    },
    {
        label: 'Other Office and Administrative Support Occupation',
        value: 'other_admin_support',
        header: false,
    },
    { label: 'Services Occupations:', value: 'header7', header: true },
    {
        label: 'Protective Service (e.g., Fire Fighting, Police Officer, Correctional Officer)',
        value: 'protective_service',
        header: false,
    },
    { label: 'Chef or Head Cook', value: 'chef', header: false },
    { label: 'Cook or Food Preparation Worker', value: 'cook', header: false },
    {
        label: 'Food and Beverage Serving Worker (e.g., Bartender, Waiter, Waitress)',
        value: 'waiter',
        header: false,
    },
    {
        label: 'Building and Grounds Cleaning and Maintenance',
        value: 'maintenance_worker',
        header: false,
    },
    {
        label: 'Personal Care and Service (e.g., Hairdresser, Flight Attendant, Concierge)',
        value: 'personalcare_worker',
        header: false,
    },
    { label: 'Sales Supervisor, Retail Sales', value: 'retail_supervisor', header: false },
    { label: 'Retail Sales Worker', value: 'retail', header: false },
    { label: 'Insurance Sales Agent', value: 'insurance_agent', header: false },
    { label: 'Sales Representative', value: 'sales_rep', header: false },
    { label: 'Real Estate Sales Agent', value: 'realestate_agent', header: false },
    { label: 'Other Services Occupation', value: 'other_services', header: false },
    {
        label: 'Agriculture, Maintenance, Repair, and Skilled Crafts Occupations:',
        value: '8',
        header: true,
    },
    {
        label: 'Construction and Extraction (e.g., Construction Laborer, Electrician)',
        value: 'construction_worker',
        header: false,
    },
    { label: 'Farming, Fishing, and Forestry', value: 'farming', header: false },
    {
        label: 'Installation, Maintenance, and Repair',
        value: 'construction_installer',
        header: false,
    },
    {
        label: 'Other Agriculture, Maintenance, Repair, and Skilled Crafts Occupation',
        value: 'other_agriculture_construction',
        header: false,
    },
    { label: 'Transportation Occupations:', value: 'header9', header: true },
    { label: 'Aircraft Pilot or Flight Engineer', value: 'pilot', header: false },
    {
        label: 'Motor Vehicle Operator (e.g., Ambulance, Bus, Taxi, or Truck Driver)',
        value: 'driver',
        header: false,
    },
    { label: 'Other Occupations:', value: 'header10', header: true },
    { label: 'Military', value: 'military', header: false },
    { label: 'Homemaker', value: 'homemaker', header: false },
    { label: 'Other Occupation', value: 'other', header: false },
    { label: "Don't Know", value: 'dont_know', header: false },
    { label: 'Not Applicable', value: 'na', header: false },
]
